image: node:12.20.1

stages:
  - deploy
  - npm
  - test



npm:
  stage: npm
  script:
    - npm config set registry ${CI_NPM_REGISTRY}
    - npm install
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - npm
  script:
    - npm run posttest
    - npm run db:create:test
    - npm run db:migrate:test
    - npm run test

deploy_production:
  image: python:3.5
  environment: production
  stage: deploy
  before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PK_PROD")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  variables:
    SSH_PK: $SSH_PK_PROD
  script:
    - scripts/deploy.sh prod@139.59.182.58
  only:
    - master


deploy_staging:
  image: python:3.5
  environment: staging
  stage: deploy
  before_script:
    - apt-get update -qq
    - apt-get install -qq git
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo '$SSH_PK_STAGING'
    - ssh-add <(echo "$SSH_PK_STAGING")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  variables:
    SSH_PK: $SSH_PK_STAGING
  script:
    - scripts/deploy_staging.sh staging@139.59.182.58
  only:
    - staging